### ISSUE TITLE
V1.10.1 - Cannot download folder/files with blank space or special characters in path/name.

### ISSUE THREAD

**Issue by Djeex** [garethgeorge/backrest#972]
**Describe the bug**
The "download" files/folder features seems to be broken for files with space or some accents in their name. It seems the path is encoded and add % for blank space, or other code character for some accents.

**To Reproduce**

1. Backup a file with a blank space, as `Cyberpunk 2077` or `Données`
2. Browse your snapshot
3. Select the folder/file
4. Try to download it
5. See error in logs :

```
error dumping snapshot: command "/bin/restic dump 84bd1130e23381cf8f929ea39a41db0a861c986fd17828ea6ab387ee98bafcf5 userdata/images/Cy..." failed: exit status 1
Output:
Fatal: cannot dump file: path "/userdata/images/Cyberpunk%202077" not found in snapshot
```
```
error dumping snapshot: command "/bin/restic dump 84bd1130e23381cf8f929ea39a41db0a861c986fd17828ea6ab387ee98bafcf5 userdata/software/..." failed: exit status 1
Output:
Fatal: cannot dump file: path "/userdata/software/Donn%C3%A9es" not found in snapshot
```

**Expected behavior**
The folder/file should download.

**Screenshots**
<img width="230" height="168" alt="Image" src="https://github.com/user-attachments/assets/2f136541-8e23-412a-a1bf-31a92c3bfa95" />
<img width="242" height="119" alt="Image" src="https://github.com/user-attachments/assets/6df8d864-dda8-4153-9ec6-6f8912b4ac67" />

<img width="1209" height="124" alt="Image" src="https://github.com/user-attachments/assets/1051819d-cad6-4287-bb29-5c9b8c65947f" />
<img width="1132" height="106" alt="Image" src="https://github.com/user-attachments/assets/7aaff0e2-4417-4d68-b594-5d2d33e57cc7" />

**Platform Info**

- Debian 13.1 AMD64
- Backrest 1.10.1

**Comment by ziotibia81** [comment]
Same issue downloading this file:

Path Info for /\\192.168.1.35\c$/DirectX.ini
{
  "name": "DirectX.ini",
  "type": "file",
  "path": "/\\\\192.168.1.35\\c$/DirectX.ini",
  "size": "40",
  "mode": "438",
  "mtime": "2017-10-26T16:53:39.1679308+02:00",
  "atime": "2017-10-26T16:53:39.1679308+02:00",
  "ctime": "2017-10-26T16:53:39.1679308+02:00"
}

---------------

error dumping snapshot: command "/root/.local/share/backrest/restic dump 3d8f5bc4c1d7bab525dee2fe36abb02308f9cb9c403ac142648791ec0624..." failed: exit status 1
Output:
Fatal: cannot dump file: path "/192.168.1.35" not found in snapshot

**Comment by garethgeorge** [comment]
Thanks for the report. Missed this, turns out I use very few (if any) paths with spaces in my test filesystem. Should be fixed by https://github.com/garethgeorge/backrest/commit/5585c207c957cd3a821c0dc069032c77e136579e

**Comment by Djeex** [comment]
> Thanks for the report. Missed this, turns out I use very few (if any) paths with spaces in my test filesystem. Should be fixed by [5585c20](https://github.com/garethgeorge/backrest/commit/5585c207c957cd3a821c0dc069032c77e136579e)

Thanks **to you** for your amazing work. Backrest is so good, it is a crucial part of my setup.

**Comment by cutix65** [comment]
1.10.1 Version 

Still this error occurs. Please can you provide a new version ?

**Comment by nicktheone** [comment]
I can confirm it's still happening with 1.10.1. Furthermore, is this just a recovery problem with the file's path or is the actual snapshot corrupted? Can you please answer this? It's pretty crucial and I'd like to know how screwed I am. Thanks for the hard work.

@garethgeorge

**Comment by lpcvoid** [comment]
I ran into the same issue with spaces. I also never use them, but some of my users do :)

**Comment by garethgeorge** [comment]
> I can confirm it's still happening with 1.10.1. Furthermore, is this just a recovery problem with the file's path or is the actual snapshot corrupted? Can you please answer this? It's pretty crucial and I'd like to know how screwed I am. Thanks for the hard work.
> 
> [@garethgeorge](https://github.com/garethgeorge)

Sorry you ran into this -- this is a download feature issue only, you can use the restore to path feature to restore the files to a specific location on your disk. Or you can restore directly with restic cli as a workaround until the next release, aiming to get this out early in the new year.

**Comment by Djeex** [comment]
> > I can confirm it's still happening with 1.10.1. Furthermore, is this just a recovery problem with the file's path or is the actual snapshot corrupted? Can you please answer this? It's pretty crucial and I'd like to know how screwed I am. Thanks for the hard work.
> > [@garethgeorge](https://github.com/garethgeorge)
> 
> Sorry you ran into this -- this is a download feature issue only, you can use the restore to path feature to restore the files to a specific location on your disk. Or you can restore directly with restic cli as a workaround until the next release, aiming to get this out early in the new year.

Take your time, you did an amazing job so far !

**Comment by GyufiThePenguin** [comment]
I’m running into the same issue and can confirm it’s not a snapshot corruption problem, only a download path handling bug.

From what I can see, the [Download] feature ends up calling restic dump with a URL-encoded path (spaces as %20, accented UTF-8 characters as %C3%A9, etc.). Restic expects the literal path exactly as stored in the snapshot, so it fails with path not found in snapshot.

So the data itself is safe, the issue is just that the download action passes an encoded path instead of the raw snapshot path.

Thanks again for the great work on Backrest, it became a core part of my setup.
